### ISSUE TITLE
Refreshing theme reloads help.erb

### ISSUE THREAD

**Issue by angelo** [jphastings/thimblr#1]
Usually, I'd want it to just reload the theme to see my changes. The help link in the header could bring you back to help.erb.

**Comment by jphastings** [comment]
When you say 'refreshing theme' do you mean pressing the refresh button in your browser? Or re-selecting it from the drop-down list? At the moment I'm using an iframe (a hold-over from Thimblr's parent, Thimble) - but I think browsers would handle this better if I used fully-fledged frames. - Thanks!

**Comment by jphastings** [comment]
I've changed to 'proper' frames, hopefully this should work as you expect now!

**Comment by angelo** [comment]
Perfect, thanks!
