### ISSUE TITLE
Needs json gem as dependency

### ISSUE THREAD

**Issue by ghost** [jphastings/thimblr#2]
When I installed Thimblr and fired it up, I got an error that the json gem was missing.

**Comment by jphastings** [comment]
Appreciate the tip! I had assumed json is bundled with ruby - I'll make the change, cheers!

If you manually install the json gem does Thimblr work?

**Comment by ghost** [comment]
Great :) Yes after I installed the json gem Thimblr worked

**Comment by jphastings** [comment]
Sweet! I've bumped the version and pushed the gem so others won't have this problem now. Thanks!
