### ISSUE TITLE
Themes not showing up in the list

### ISSUE THREAD

**Issue by jbrewer** [jphastings/thimblr#3]
Just intalled this to play around and everything seems to be working except the themes. It even imported my data, but still no themes show in the dropdown. I confirmed the files are in the correct place. Any help would be appreciated!

**Comment by jphastings** [comment]
It's a shame you only just noticed - I've just moved home so I'm stuck on my iPhone as a sole connection to the web for a few weeks! I'll see if I can figure out what's wrong from here but it may be a while before I have a fix for you, sorry!

If you could post a breakdown of your environment here it'd be handy - windows? Ruby version? List of installed gems? Thanks!

**Comment by tmilewski** [comment]
What seems to be happening is that Thimblr is not creating the themes directory under ~/Library/Application Support/Thimblr and simply placing the themes in that directory.

Quick fix for jbrewer: Create themes dir in the aforementioned path and move the .html files into there.
