### ISSUE TITLE
I've ported thimblr to a stripped down version - "Thimblr Base"

### ISSUE THREAD

**Issue by jasonseney** [jphastings/thimblr#8]
Hi, I've ported the core of thimblr over to a new project in case anyone is interested. In addition to a few bug fixes, I've set up the application much differently:
- Uses bundler for dependencies
- Can easily be run as a rack application
- All theme and data settings are changed by hand in config
- Theme and data files can exist anywhere on computer (good for switching between source controlled projects)
- Theme runs at application root (`/`)

I also hope to add additional support for some of the missing tumblr elements as well.

The project is located on [GitHub - Thimblr Base](https://github.com/jasonseney/thimblr-base)

I apologize for not forking and submitting pull requests, but I really needed to rewrite the non-parser code to better fit my workflow.

Thanks for checking it out!

**Comment by jphastings** [comment]
No worries at all! Thanks for letting me know :) I'll have a look through it this weekend - cheers!
